# Site settings
title: Saeed Vahdani
email: thesaeedvahdani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: thesaeedvahdani
github_username: saeedvahdani
linkedin_username: saeedvahdani
stack_username: 8495032/saeedvahdani
telegram_username: saeedvahdani
instagram_username: thesaeedvahdani/
facebook_username: saeedvahdani/
medium_username: saeedvahdani
kaggle_username: saeedvahdani

# Build settings
markdown: kramdown
